### ISSUE TITLE
关于时间

### ISSUE THREAD

**Issue by Stefan-084** [INVOKERer/LoFormer#15]
作者您好，在了解您这项工作的时候，尝试推理一张1024 * 1024大小的图（网络是Big，不切patch），时间花销高达80s，机器是A100，请问这个时间正常吗？

**Comment by INVOKERer** [comment]
可能正常，我的model里dct默认用了mlp的形式，所以dct系数初始化会在一开始占用较长的时间，不知道你的80s算入模型初始化时间了么，算了的话是有可能的，这个网络正常推理需要sliding window。

**Comment by Stefan-084** [comment]
时间从 model.eval()执行完以后开始算的
________________________________
发件人: XIntian Mao ***@***.***>
发送时间: Thursday, December 19, 2024 10:19:16 PM
收件人: INVOKERer/LoFormer ***@***.***>
抄送: Ruizhe GUO 郭锐哲 ***@***.***>; Author ***@***.***>
主题: Re: [INVOKERer/LoFormer] 关于时间 (Issue #15)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

可能正常，我的model里dct默认用了mlp的形式，所以dct系数初始化会在一开始占用较长的时间，不知道你的80s算入模型初始化时间了么，算了的话是有可能的，这个网络正常推理需要sliding window。

―

**Comment by INVOKERer** [comment]
emmm，要不先用test.yml试试推理时间是否正常？

**Comment by Stefan-084** [comment]
您好，训练的时候不需要 train_size 这个参数，推理时需要指定这个参数，是这样嘛，在这之前我推理时加载的 config 是和训练时一样的文件
________________________________
发件人: XIntian Mao ***@***.***>
发送时间: Thursday, December 19, 2024 10:30:08 PM
收件人: INVOKERer/LoFormer ***@***.***>
抄送: Ruizhe GUO 郭锐哲 ***@***.***>; Author ***@***.***>
主题: Re: [INVOKERer/LoFormer] 关于时间 (Issue #15)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

emmm，要不先用test.yml试试推理时间是否正常？

―

**Comment by INVOKERer** [comment]
是的，推理时需要指定这个参数。

**Comment by Stefan-084** [comment]
好的谢谢您的解答
