### ISSUE TITLE
Alternative download links

### ISSUE THREAD

**Issue by 0asa** [INVOKERer/LoFormer#2]
Dear Authors,

Firstly, I would like to extend my gratitude for your work on LoFormer for image deblurring. The model looks promising, and I am eager to test it on my images. However, I have encountered a challenge with downloading the model weights. The provided link directs to Baidu Cloud, which requires the installation of a BaiduNetdisk application. While I appreciate the effort, I have a few concerns:

1. Installing additional software solely for downloading a file feels a bit like being asked to buy a new car just to drive to the grocery store. Many users, including myself, prefer not to install unfamiliar applications that might have access to sensitive data or could affect system performance.
2. Accessibility and Convenience: Requiring specific software for file downloads can be a barrier to accessibility. It limits the ease with which researchers can access and test your model, potentially reducing the impact and reach of your work. Not everyone wants to jump through hoops just to get a file.
3. Reproducibility in Science: One of the pillars of scientific research is reproducibility. By providing easier access to model weights, you enable a broader audience to validate and build upon your work. This not only enhances the credibility of your research but also fosters collaboration and innovation within the community. After all, reproducible science is the best science, right?

To address these concerns, it would be great to provide alternative download links for the model weights. Some suggestions include:
- Hosting the files on platforms like Google Drive, Dropbox, or OneDrive, which do not require additional software for downloads.
- Using GitHub Releases or other repositories that are commonly used in the research community (such as HuggingFace)?

Providing these alternatives would greatly facilitate the testing and adoption of LoFormer, ensuring that your work can be more readily accessed and utilized by the broader research community. Plus, it would save us all from having to clutter our systems with yet another app.

Thank you for considering this request. I look forward to your response and to testing LoFormer.
Best regards,
Vincent.

**Comment by INVOKERer** [comment]
Sure, I will provide them today. It would be slow to upload them to GoogleDrive.

**Comment by 0asa** [comment]
Thank you very much!
