### ISSUE TITLE
有没有onedrive的链接呀，百度网盘和google我都没法访问

### ISSUE THREAD

**Issue by sunzhe09** [INVOKERer/LoFormer#5]

**Comment by INVOKERer** [comment]
没用过onedrive，我明天研究下。

**Comment by INVOKERer** [comment]
https://1drv.ms/f/c/65ae13a89837afd7/EtTpDOrc3EdJjrC6ZbyVM0gBQX8z9Pp4uHbOcIitXW5vkw?e=qdkqwr
